/**
 * CSV Data Utilities
 * 
 * Reads ETF holdings data from CSV files generated by the Python pipeline.
 */

import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';

// ============================================================================
// Types (matching CSV schemas)
// ============================================================================

export interface CSVHolding {
    fund_ticker: string;
    fund_name: string;
    provider: string;
    as_of_date: string;
    stock_ticker: string;
    stock_name: string;
    cusip: string;
    isin: string;
    weight: number;
    shares: number;
    market_value: number;
}

export interface CSVStock {
    ticker: string;
    name: string;
    cusip: string;
    isin: string;
    sector: string;
    industry: string;
    market_cap: number;
    exchange: string;
}

export interface CSVFund {
    ticker: string;
    name: string;
    provider: string;
    total_holdings: number;
    as_of_date: string;
    collected_at: string;
}

// ============================================================================
// CSV Loading
// ============================================================================

function loadCSV<T>(filename: string): T[] {
    const filePath = path.join(process.cwd(), 'lib', 'data', filename);

    if (!fs.existsSync(filePath)) {
        console.warn(`CSV file not found: ${filePath}`);
        return [];
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    return parse(content, {
        columns: true,
        skip_empty_lines: true,
        cast: true,  // Auto-convert numbers
    });
}

// ============================================================================
// Cached Loaders
// ============================================================================

let holdingsCache: CSVHolding[] | null = null;
let stocksCache: CSVStock[] | null = null;
let fundsCache: CSVFund[] | null = null;

export function getCSVHoldings(): CSVHolding[] {
    if (!holdingsCache) holdingsCache = loadCSV<CSVHolding>('holdings.csv');
    return holdingsCache;
}

export function getCSVStocks(): CSVStock[] {
    if (!stocksCache) stocksCache = loadCSV<CSVStock>('stocks.csv');
    return stocksCache;
}

export function getCSVFunds(): CSVFund[] {
    if (!fundsCache) fundsCache = loadCSV<CSVFund>('funds.csv');
    return fundsCache;
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get all funds that hold a specific stock.
 */
export function getFundsHoldingStock(ticker: string): CSVHolding[] {
    return getCSVHoldings().filter(h => h.stock_ticker === ticker);
}

/**
 * Get all holdings for a specific fund.
 */
export function getFundHoldings(fundTicker: string): CSVHolding[] {
    return getCSVHoldings().filter(h => h.fund_ticker === fundTicker);
}

/**
 * Get stock info by ticker.
 */
export function getStock(ticker: string): CSVStock | undefined {
    return getCSVStocks().find(s => s.ticker === ticker);
}

/**
 * Get fund info by ticker.
 */
export function getFund(ticker: string): CSVFund | undefined {
    return getCSVFunds().find(f => f.ticker === ticker);
}

/**
 * Check if CSV data is available.
 */
export function hasCSVData(): boolean {
    const holdingsPath = path.join(process.cwd(), 'lib', 'data', 'holdings.csv');
    return fs.existsSync(holdingsPath);
}

/**
 * Clear the cache (useful for testing or when data is updated).
 */
export function clearCSVCache(): void {
    holdingsCache = null;
    stocksCache = null;
    fundsCache = null;
}
